#!/usr/bin/env python3
"""Generate reference/DRAFTS.md — a private index of every client draft.

Scans draft/<slug>/ pages and their reference/clients/<slug>.md fact sheets and
writes a Markdown table (company, live URL, status, contact). Run it after adding
or updating a draft:  python3 scripts/build_admin.py

Lives under reference/ (and scripts/), which .vercelignore keeps OUT of the
deployed site — this list of prospects is never published on lemonelly.com.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DRAFT_DIR = ROOT / "draft"
CLIENTS_DIR = ROOT / "reference" / "clients"
OUT = ROOT / "reference" / "DRAFTS.md"
LIVE_BASE = "https://lemonelly.com/draft"


def first(pattern, text, default=""):
    m = re.search(pattern, text, re.IGNORECASE | re.MULTILINE)
    return m.group(1).strip() if m else default


def clean(value):
    """Strip markdown bold and trailing source/provenance notes."""
    value = value.replace("**", "")
    # cut at an em/en dash, ". Source", "Source:", "(source", "(home", "(2026"
    value = re.split(
        r"\s+[—–]\s+|\.\s*Source|\s+Source:|\s*\(source|\s*\(home|\s*\(2026",
        value,
        flags=re.IGNORECASE,
    )[0]
    return value.strip().rstrip(".")


def title_company(slug):
    idx = DRAFT_DIR / slug / "index.html"
    if not idx.exists():
        return slug
    t = first(r"<title>(.*?)(?:\s*\||</title>)", idx.read_text(encoding="utf-8"))
    return t or slug


def parse(slug):
    fact = CLIENTS_DIR / f"{slug}.md"
    company, phone, email, status = title_company(slug), "", "", "drafted?"
    if fact.exists():
        text = fact.read_text(encoding="utf-8")
        h = first(r"^#\s+(.*)$", text)
        if h:
            company = clean(re.split(r"\s+[—–]\s+", h)[0])
        phone = clean(first(r"^-?\s*Phone[^:]*:\s*(.+)$", text)) or "—"
        email = clean(first(r"^-?\s*Email[^:]*:\s*(.+)$", text)) or "—"
        status = first(r"^Status:\s*(.+)$", text) or "drafted?"
    return company, phone, email, status


def main():
    slugs = sorted(p.name for p in DRAFT_DIR.iterdir() if (p / "index.html").exists())
    rows = []
    counts = {}
    for slug in slugs:
        company, phone, email, status = parse(slug)
        key = status.split()[0].lower() if status else "unknown"
        counts[key] = counts.get(key, 0) + 1
        url = f"{LIVE_BASE}/{slug}"
        rows.append(
            f"| {company} | [`/draft/{slug}`]({url}) | {status} | {phone} | {email} |"
        )

    summary = " · ".join(f"{n} {k}" for k, n in sorted(counts.items()))
    lines = [
        "# Client drafts — tracker",
        "",
        "_Generated by `python3 scripts/build_admin.py` — do not hand-edit._",
        "Private: `reference/` is excluded from the deployed site via `.vercelignore`.",
        "To change a draft's status, edit its `reference/clients/<slug>.md` `Status:` "
        "line, then re-run the script.",
        "",
        f"**{len(slugs)} drafts** — {summary}",
        "",
        "| Company | Draft URL | Status | Phone | Email |",
        "|---|---|---|---|---|",
        *rows,
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(slugs)} drafts)")


if __name__ == "__main__":
    main()
